# Generated by Django 4.0.2 on 2022-05-14 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComposerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(help_text='Введите ФИО композитора', max_length=50)),
                ('biography', models.TextField(help_text='Введите биографию композитора', null=True)),
                ('date_of_birth', models.CharField(help_text='Введите дату рождения композитора', max_length=30)),
                ('date_of_death', models.CharField(help_text='Введите дату смерти композитора', max_length=30, null=True)),
                ('photo', models.TextField(help_text='Введите ссылку на фото композитора', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите жанр музыкального произведения', max_length=30)),
                ('definition', models.TextField(help_text='Введите определение жанра')),
                ('history', models.TextField(help_text='Введите историю жанра', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название музыкального произведения', max_length=65)),
                ('description', models.TextField(help_text='Введите краткое описание произведения')),
                ('first_night', models.CharField(help_text='Введите дату премьеры', max_length=30, null=True)),
                ('audio', models.TextField(help_text='Введите ссылку на аудиозапись', null=True)),
                ('description_of_audio', models.TextField(help_text='Описание аудиозаписи', null=True)),
                ('composer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.composermodel')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.genremodel')),
            ],
        ),
    ]
